---
- hosts: all
  vars_files:
  - my_variables
  roles:
  - role: brew
    brew_taps: []
    brew_packages: []
    cask_packages:
      - iterm2
      - launchbar
      - google-chrome
      - 1password
      - amazon-music
      - dropbox
      - nvalt
      - viscosity
      - intellij-idea
      - microsoft-office
  - role: fubarhouse.macstore
  - role: loginitems

