---
# Configure your freshly installed software
- hosts: all
  roles:
  - role: sshkey
  - role: dock
  - role: mackup
  - role: bitbucket
  - role: capslock
  - role: loginitems
  - role: purecloud
  - role: maven
  - role: tempcreds
  tasks:
  - name: clone prezto to home directory
    git: repo=https://github.com/sorin-ionescu/prezto.git recursive=yes force=yes dest=/Users/{{ ansible_user_id }}/.zprezto
  - name: install pygments for nice color cat
    pip: name=pygments state=latest
    become: yes
    become_method: sudo

- hosts: all
  roles:
  - osxc.common-env
