---
# Configure your freshly installed software
- hosts: all
  roles:
  - role: sshkey
  - role: dock
  - role: mackup
  - role: bitbucket
  - role: capslock

- hosts: all
  roles:
  - osxc.common-env
