---
# Configure your freshly installed software
- hosts: all
  vars_files:
  - my_variables
  roles:
  - role: sshkey
  - role: dock
  - role: mackup
  - role: bitbucket
    inin_repos:
    - donut
    - donut-common
    - donut-events
# - role: capslock
  - role: purecloud
  - role: maven
  - role: tempcreds
  - role: spacemacs
  tasks:
  - name: clone prezto to home directory
    git: repo=https://github.com/sorin-ionescu/prezto.git recursive=yes force=yes dest={{ ansible_user_dir }}/.zprezto
  - name: install pygments for nice color cat
    pip: name=pygments state=latest
    become: yes
    become_method: sudo
  - name: download solarized
    get_url: url=http://ethanschoonover.com/solarized/files/solarized.zip dest={{ ansible_user_dir }}/Downloads
  - name: check /etc/shells
    command: grep -q /usr/local/bin/zsh /etc/shells
    register: shells_modified
    failed_when: False
    changed_when: False
  - name: add /usr/local/bin/zsh to /etc/shells
    shell: echo /usr/local/bin/zsh | sudo tee -a /etc/shells
    when: "shells_modified.rc == 1"
  - name: set shell to /usr/local/bin/zsh
    command: chsh -s /usr/local/bin/zsh
    when: "\"{{ ansible_env['SHELL'] }}\" != \"/usr/local/bin/zsh\""
