---
# Here we describe every software we may want to install
- hosts: all
  roles:
  - role: osxc.packages
    brew_taps:
    - caskroom/fonts
    - railwaycat/homebrew-emacsmacport
    brew_packages:
    - git
    - zsh
    - tree 
    - the_silver_searcher
    - maven
    - wget
    - tmux
    - httpie
    - boot-clj
    - jq
    cask_packages:
    - font-anonymous-pro
    - iterm2
    - launchbar
    - opera
    - 1password
    - amazon-music
    - dropbox
    - nvalt
    - java
    - intellij-idea
  tasks:
    - name: emacs-mac
      homebrew: name=emacs-mac state=present install_options=with-spacemacs-icon
