---
- hosts: all
  vars_files:
  - my_variables
  tasks:
  - name: Install Emacs
    homebrew_cask: 
      name: emacs-mac
      state: present
      install_options: with-spacemacs-icon
  roles:
  - sdkman
  - role: brew 
    brew_taps:
    - caskroom/fonts
    - railwaycat/homebrew-emacsmacport
    brew_packages:
    - git
    - zsh
    - tree 
    - the_silver_searcher
    - awscli
    - wget
    - tmux
    - httpie
    - boot-clj
    - jq
    - maven
    cask_packages:
    - font-anonymous-pro
    - font-source-code-pro
    - font-source-code-pro-for-powerline

