---
- hosts: all
  vars_files:
  - my_variables
  roles:
  - sdkman
  - role: brew 
    brew_taps:
    - caskroom/fonts
    - railwaycat/homebrew-emacsmacport
    - argon/mas
    brew_packages:
    - git
    - zsh
    - mas
    - tree 
    - the_silver_searcher
    - awscli
    - wget
    - tmux
    - httpie
    - boot-clj
    - jq
    cask_packages:
    - font-anonymous-pro
    - emacs-mac
#   - iterm2
#   - launchbar
#   - opera
#   - 1password
#   - amazon-music
#   - dropbox
#   - nvalt
#   - emacs-mac
#   - viscosity
#   - intellij-idea
#   - microsoft-office
