---
- hosts: all
  vars_files:
  - my_variables
  roles:
  - sdkman
  - role: brew 
    brew_taps:
    - caskroom/fonts
    - railwaycat/homebrew-emacsmacport
    brew_packages:
    - git
    - zsh
    - tree 
    - the_silver_searcher
    - awscli
    - wget
    - tmux
    - httpie
    - boot-clj
    - jq
    cask_packages:
    - font-anonymous-pro
    - emacs-mac
