---
# ensure that we have java upfront
- hosts: all
  roles:
  - role: osxc.packages
    cask_packages:
    - java

- hosts: all
  vars_files:
  - my_variables
  roles:
  - role: osxc.packages
    brew_taps:
    - caskroom/fonts
    - railwaycat/homebrew-emacsmacport
    - argon/mas
    brew_packages:
    - git
    - zsh
    - mas
    - tree 
    - the_silver_searcher
    - awscli
    - maven
    - wget
    - tmux
    - httpie
    - boot-clj
    - jq
    cask_packages:
    - font-anonymous-pro
    - iterm2
    - launchbar
    - opera
    - 1password
    - amazon-music
    - dropbox
    - nvalt
    - emacs-mac
    - viscosity
    - intellij-idea
    - microsoft-office
  - role: yta.osx-mas
