---
# ensure that we have java upfront
- hosts: all
  roles:
  - role: osxc.packages
    cask_packages:
    - java

- hosts: all
  vars_files:
  - my_variables
  roles:
  - role: osxc.packages
    brew_packages:
    - maven
    - git
    - awscli
    - jq
  - role: sshkey
#  - role: bitbucket
#  - role: purecloud
  - role: maven
#  - role: tempcreds
