- homebrew: name=mackup state=present
- copy: src=.mackup.cfg dest={{ ansible_user_dir }}/.mackup.cfg
- name: restoring configurations from backup
  command: mackup restore --force creates={{ ansible_user_dir }}/.spacemacs 
