- name: download PureCloud package
  get_url: url=https://dhqbrvplips7x.cloudfront.net/directory-mac/1.7.214/purecloud-mac-1.7.214.pkg dest=/Users/{{ ansible_user_id }}/Downloads/purecloud-mac-1.7.214.pkg
- name: install PureCloud app
  command: sudo installer -pkg /Users/{{ ansible_user_id }}/Downloads/purecloud-mac-1.7.214.pkg -target / creates=/Applications/PureCloud.app
