- name: Install homebrew
  shell: >
         ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
         creates=/usr/local/Cellar
- name: Install homebrew taps
  homebrew_tap: tap={{ item }} state=present
  with_items: "{{ brew_taps }}"

- name: Install the homebrew packages
  homebrew: name={{ item }} state=latest
  with_items: "{{ brew_packages }}"

- name: Install the cask packages
  homebrew_cask: name={{ item }}
  with_items: "{{ cask_packages }}"
