- name: get the keyboard product ID
  shell: ioreg -n IOHIDKeyboard -r | grep -e 'class IOHIDKeyboard' -e VendorID\" -e ProductID | grep ProductID | head -n 1 | grep -o \\d\\+
  register: product_id
  changed_when: False

- name: get the keyboard vendor ID
  shell: ioreg -n IOHIDKeyboard -r | grep -e 'class IOHIDKeyboard' -e VendorID\" -e ProductID | grep VendorID | head -n 1 | grep -o \\d\\+
  register: vendor_id
  changed_when: False

- name: remap caps lock key
  shell: defaults -currentHost write -g com.apple.keyboard.modifiermapping.{{ vendor_id.stdout }}-{{ product_id.stdout }}-0 '<array><dict><key>HIDKeyboardModifierMappingDst</key><integer>2</integer><key>HIDKeyboardModifierMappingSrc</key><integer>0</integer></dict></array>'
